### ISSUE TITLE
Wrong author maybe?

### ISSUE THREAD

**Issue by facuspagnuolo** [vasa-develop/ethereum-in-depth#2]
See https://github.com/vasa-develop/ethereum-in-depth/blob/e1319399d5c5ee81bf315981162b199a82593a91/1-contract-creation/package.json#L7

![image](https://user-images.githubusercontent.com/6967192/51144104-f0431080-182e-11e9-86ab-0938ff5b3fb8.png)

**Comment by vasa-develop** [comment]
ah. Should have cloned it.
Anyways, I added we both as contributors.

Thanks for the heads up :)
